SolarPlots2014/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace SolarPlots2014.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl)
        {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

SolarPlots2014/Views/Shared/_Layout.Mobile.cshtml
@{
    ViewBag.Title = "_Layout.Mobile.cshtml";
}



<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/jquery")

    @Scripts.Render("~/bundles/knockout")
    <link rel="stylesheet" href="~/content/bootstrap.css" />
    <link rel="stylesheet" href="~/content/bootstrap-datetimepicker.css" />

    @Scripts.Render("~/bundles/modernizr")
    
    <link rel="icon" href="~/images/favicon.ico" type="image/x-icon" />
    <meta name="description" content="Plot the sun's angle position on the horizon for any location in the United States">
    <meta name="keywords" content="sun, solar, astronomy, plot, photography, sundial">
    @RenderSection("head", required: false)
    @RenderSection("HeadJavaScript", required: false)
</head>
<body>
    <div>
        @RenderBody()

    </div><!-- /page -->
    @RenderSection("scripts", required: false)
</body>
</html>

SolarPlots2014/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")    
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/bundles/knockout")
    <link rel="icon" href="~/images/favicon.ico" type="image/x-icon" />
    <meta name="description" content="Plot the sun's angle position on the horizon for any location in the United States">
    <meta name="keywords" content="sun, solar, astronomy, plot, photography, sundial">
    @RenderSection("head", required: false)

</head>
<body>
    @RenderBody()


    @RenderSection("scripts", required: false)
</body>
</html>

SolarPlots2014/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
        else
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}
else
{
    
}